<?php $invalids = array ( 	'dupes' => array(		'Duplicate'	)
	, 'dataInvalid' => array(		'URL Rejected', 'timeout', 'No Data Sent', 'Data Rejected', 
'User Declined', 
'', 
'Invalid Email Address', 
'Indeterminate Email Address (catchall servers)', 
'Verified Email Address', 
'Email was NOT verified', 
'Invalid email format.', 
'International domain name in email address', 
'Numeric repetition', 
'Pattern indicates Junk marley', 
'Email Domain Associated with Manufactured Records', 
'matches pattern: nigg [no antipattern]', 
'Pattern indicates Junk .js', 
'Misspelled domain name in email address', 
'Email Domain Matches: "\.con$" [no antipattern]', 
'matches pattern: pimp [no antipattern]', 
'Pattern Indicates Junk dirt', 
'Pattern indicates Junk free', 
'Email Domain Matches email.com', 
'Email Prefix ends in dash', 
'Email Prefix Too Short .com', 
'Fake email address domain', 
'matches pattern: shit [no antipattern]', 
'Matches yourmom', 
'Matches sexy', 
'matches pattern: piss [no antipattern]', 
'Pattern indicates Junk ilove', 
'matches pattern: bastard [no antipattern]', 
'Matches sexi', 
'Pattern indicates profanity stupid', 
'Email Address is only numbers', 
'Matches trap', 
'matches pattern: arse [no antipattern]', 
'Letter Repetition - 4char', 
'Matches test', 
'Matches hores', 
'matches pattern: Cock [no antipattern]', 
'Pattern indicates Junk .jj', 
'Pattern indicates junk hdz', 
'Invalid has double period', 
'Email Address starts with test', 
'matches pattern: bitch [no antipattern]', 
'Pattern indicates Junk kill', 
'Pattern indicates Junk lick', 
'matches pattern: Biatch [no antipattern]', 
'Pattern indicates Junk marly', 
'Pattern indicates Junk kiss', 
'Pattern Indicates Junk death', 
'Matches asdfgh', 
'Matches ^ass', 
'Email Address Matches: "mailinator" [no antipattern]', 
'Email Address starts with pimp', 
'matches pattern: dyke [no antipattern]', 
'matches pattern: "spam" [no antipattern]', 
'Matches Troll', 
'Email Domain Matches embarqmail', 
'Matches: "qq" [no antipattern]', 
'matches pattern: jizz [no antipattern]', 
'Letter Repetition - 5char', 
'matches pattern: fanny [no antipattern]', 
'Pattern indicates Junk gmail', 
'Matches ^Clit', 
'Matches: "rofl" [no antipattern]', 
'matches fake', 
'matches pattern: "junk" [no antipattern]', 
'matches pattern: poop [no antipattern]', 
'Pattern indicates profanity fuku', 
'matches pattern: twat [no antipattern]', 
'Invalid ends with period', 
'Gov Domain pattern: "\.gov$" [no antipattern]', 
'matches pattern: titt [no antipattern]', 
'Pattern Indicates Profanity butt', 
'matches pattern: tits [no antipattern]', 
'matches pattern: queer [no antipattern]', 
'Matches fuckyou', 
'matches pattern: nazi [no antipattern]', 
'matches pattern: lesbian [no antipattern]', 
'Email Address Matches: "wowway" [no antipattern]', 
'Matches sexxy', 
'Pattern indicates profanity kyou', 
'Pattern indicates profanity hole', 
'Email domain indicates military', 
'matches pattern: fcuk [no antipattern]', 
'Pattern Indicates profanity suck', 
'Email address starts with info', 
'Pattern indicates Junk loser', 
'Pattern indicates Junk fgre', 
'Pattern Indicates Junk blah', 
'matches pattern: turd [no antipattern]', 
'matches pattern: "seed" (appleseed|cottonseed|hayseed|linseed|birdseed)', 
'Reserved Domain example\.(com|net|org|info|gov|edu)', 
'Pattern indicates junk hjk', 
'Matches qwerty', 
'Pattern Indicates Junk murder', 
'Pattern indicates Junk iwant', 
'matches pattern: fart [no antipattern]', 
'Pattern indicates Junk ihate', 
'Pattern indicates Junk ben10', 
'Pattern indicates Junk anonym', 
'matches pattern: semen [no antipattern]', 
'Pattern Indicates Junk dont', 
'Matches Hitler', 
'Matches: "asdf" [no antipattern]', 
'matches pattern: penis [no antipattern]', 
'Matches sfsf', 
'Matches ^screw', 
'matches pattern: slut [no antipattern]', 
'Pattern Indicates Profanity crack', 
'Matches skdf', 
'matches pattern: pussy [no antipattern]', 
'Pattern indicates profanity starts with eat', 
'Matches sdfd', 
'Pattern indicates Profanity titty', 
'Email Address or name starts with fag', 
'Invalid starts with period', 
'Filter not found.', 
'Bad Domain', 
'Pattern indicates Junk donot', 
'Matches sdfs', 
'matches pattern: fuck [no antipattern]', 
'Matches c(u|4)nt', 
'matches pattern: scrotum [no antipattern]', 
'Email address starts with example', 
'Matches: "lmao" [no antipattern]', 
'matches pattern: jism [no antipattern]', 
'Email address starts with admin', 
'Pattern indicates profanity yourself', 
'Pattern indicates profanity fck', 
'Invalid Email', 
'First Name is Invalid.', 
'Last Name is Invalid.', 
'Phone is Invalid.', 
'URL is Invalid.', 
'IP is Invalid.', 
'No User Given.', 
'Bad Email', 
'First Name is missing.', 
'Zip is Invalid.', 
'Phone number is Invalid.', 
'Email is Invalid.', 
'No signup date given.', 
'Forte Mail Verify Failed', 
'MySQL Failure: Check duplicates failed', 
'Test Post', 
'City is Invalid.', 
'First Name missing letters.', 
'First Name has invalid characters.', 
'First name is not missing numbers.', 
'First Name has more than 30 characters.'	
, 'Bad State to Phone'
, 'Area Code / State Mismatch'
,'No Call State'
)
	, 'refused' => array(		'Lead Declined'
		, 'Feed deactivated.'
		 ,'Budget reached for 500392'
		,'Before 8 AM Denied on this Feed'	
		,'Before 10 AM Denied on this Feed'
		, 'Daily budget reached.'
		, 'MYSQL Failure: select orders list failed'
		)); ?>